- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create key pair
      # use no_log to avoid private key being displayed into output
      amazon.aws.ec2_key:
        name: sample
        region: us-east-1
      register: keyout

   #- name: print key
   #  debug:
   #    var: keyout
    - name: start an instance
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "sample"
          #vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
          #network_interfaces:
          #- assign_public_ip: true
        image_id: ami-05b10e08d247fb927
        exact_count: 1
        region: us-east-1
        tags:
          Environment: Testing
    - name: save key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample.pem
      when: keyout.changed == True
