---
- name: Install Oracle Database on Oracle Linux
  hosts: oracle-linux
  become: true
  become_user: vascon
  tasks:
    - name: Example task using opitzconsulting.ansible_oracle
      opitzconsulting.ansible_oracle.:
        parameter_1: value
        parameter_2: value
        
